name: Build Windows ARM64

on:
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Restore NuGet Packages
      run: nuget restore 3DSRNGTool.sln

    - name: Build ARM64 Executable
      run: |
        msbuild 3DSRNGTool.sln /p:Configuration=Release /p:Platform=ARM64 /p:TargetFrameworkVersion=v4.8

    - name: Upload ARM64 Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 3DSRNGTool-Windows-ARM64
        path: 3DSRNGTool/bin/ARM64/Release/
